### ISSUE TITLE
latest version of light-4j is 1.5.28, but dependence list in hydrid-command, hydrid-query and user-management (maybe more?) uses version 1.5.29

### ISSUE THREAD

**Issue by lanphan** [networknt/light-portal#79]
Please check again, thanks.

**Comment by stevehu** [comment]
@lanphan This was a mistake I made two weeks ago. The light-portal is under heavy development and the 1.5.29 was supposed to be released two weeks ago but delayed due to the config feature is incomplete. I merged two quickly for the light-portal :) This won't happen again. Thanks a lot for bringing it up.

**Comment by stevehu** [comment]
One developer asked a question about how to build light-portal and I answered him in email and posted on the stackoverflow as well. https://stackoverflow.com/questions/54653349/how-to-build-and-run-the-light-portal-from-light-4j-platform Hope it helps.

**Comment by lanphan** [comment]
@stevehu I managed to make it work by degrading all relating light-4j libs to 1.5.28, but still waiting for your fix, thanks.

I did read through all your documents about Light portal, thanks for your great framework.

**Comment by stevehu** [comment]
This should be resolved with the new releases. It is highly recommended to use the 2.0.x release if possible.
